In [7]:
import pandas as pd
df = pd.read_csv(r"C:\Users\ramba\OneDrive\Documents\AI\students_dataset_rows (1).csv")

In [8]:
df

,Student_ID,First_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
0,1215,Rohan,Yadav,24,Female,MBA,1,7.22,77.0,57,Warangal,Java,Placed,No,False,2023-04-02
1,1287,Teja,Sharma,21,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Patel,20,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Gupta,19,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
4,1225,Aditya,Rao,22,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1092,Akash,Kumar,23,Female,DS,2,5.96,66.0,60,Bangalore,SQL,Placed,Yes,True,2024-09-01
296,1082,Divya,Sharma,19,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,No,True,2023-02-25
297,1229,Sneha,Reddy,24,Male,EEE,4,6.40,51.0,61,Bangalore,Cloud,Not Placed,Yes,False,2024-05-14
298,1072,Sai,Verma,23,Female,CIVIL,3,5.99,NaN,95,Hyderabad,SQL,Not Placed,Yes,True,2023-10-13
299,1264,Kiran,Sharma,25,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,Yes,False,2023-02-27

In [12]:
df.head(10)

,Student_ID,First_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
0,1215,Rohan,Yadav,24,Female,MBA,1,7.22,77.0,57,Warangal,Java,Placed,No,False,2023-04-02
1,1287,Teja,Sharma,21,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Patel,20,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Gupta,19,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
4,1225,Aditya,Rao,22,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
5,1158,Varun,Verma,20,Male,CSE,1,9.75,92.0,41,Hyderabad,AI,Placed,Yes,True,2023-12-26
6,1009,Varun,Reddy,19,Female,MECH,1,6.82,60.0,93,Hyderabad,Cloud,Not Placed,Yes,True,2024-06-10
7,1142,Pooja,Singh,22,Male,EEE,3,NaN,64.0,52,Guntur,Java,Not Placed,No,False,2023-12-20
8,1196,Meera,Rao,20,Male,EEE,1,6.62,88.0,71,Hyderabad,Cloud,Not Placed,Yes,True,2024-02-05
9,1032,Kiran,Naidu,21,Male,DS,1,5.71,80.0,44,Guntur,AI,Placed,No,False,2023-02-14

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      300 non-null    int64
 1   First_Name      300 non-null    object
 2   Last_Name       300 non-null    object
 3   Age             300 non-null    int64
 4   Gender          300 non-null    object
 5   Department      300 non-null    object
 6   Year            300 non-null    int64
 7   CGPA            292 non-null    float64
 8   Attendance      292 non-null    float64
 9   Marks           300 non-null    int64
 10  City            292 non-null    object
 11  Course          300 non-null    object
 12  Placement       300 non-null    object
 13  Scholarship     300 non-null    object
 14  Fee_Paid        300 non-null    bool
 15  Admission_Date  300 non-null    object
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 35.6+ KB

In [14]:
df.describe()

        Student_ID         Age        Year        CGPA  Attendance       Marks
count   300.000000  300.000000  300.000000  292.000000  292.000000  300.000000
mean   1146.206667   21.463333    2.456667    7.793973   75.880137   68.030000
std      84.162869    2.338136    1.174473    1.322570   14.477000   19.054466
min    1001.000000   18.000000    1.000000    5.540000   50.000000   35.000000
25%    1073.750000   19.000000    1.000000    6.635000   64.000000   51.000000
50%    1146.500000   21.500000    2.000000    7.820000   77.000000   70.000000
75%    1219.250000   23.000000    4.000000    8.960000   89.000000   85.000000
max    1290.000000   25.000000    4.000000    9.980000  100.000000  100.000000

In [16]:
df.shape

(300, 16)

In [17]:
df.columns

Index(['Student_ID', 'First_Name', 'Last_Name', 'Age', 'Gender', 'Department',
       'Year', 'CGPA', 'Attendance', 'Marks', 'City', 'Course', 'Placement',
       'Scholarship', 'Fee_Paid', 'Admission_Date'],
      dtype='object')

In [18]:
df.index

RangeIndex(start=0, stop=300, step=1)

In [19]:
df.dtypes

Student_ID          int64
First_Name         object
Last_Name          object
Age                 int64
Gender             object
Department         object
Year                int64
CGPA              float64
Attendance        float64
Marks               int64
City               object
Course             object
Placement          object
Scholarship        object
Fee_Paid             bool
Admission_Date     object
dtype: object

In [20]:
df.loc[10]

Student_ID              1278
First_Name              Teja
Last_Name              Singh
Age                       25
Gender                  Male
Department                AI
Year                       3
CGPA                    7.51
Attendance              91.0
Marks                     66
City               Hyderabad
Course                 Cloud
Placement         Not Placed
Scholarship               No
Fee_Paid                True
Admission_Date    2023-01-31
Name: 10, dtype: object

In [21]:
df.loc[0:4,["First_Name","Department","CGPA"]]

  First_Name Department  CGPA
0      Rohan        MBA  7.22
1       Teja        MBA  6.98
2      Meera         AI  9.04
3     Aditya        MBA  8.62
4     Aditya        CSE  7.24

In [22]:
df.iloc[0:5,0:3]

   Student_ID First_Name Last_Name
0        1215      Rohan     Yadav
1        1287       Teja    Sharma
2        1235      Meera     Patel
3        1065     Aditya     Gupta
4        1225     Aditya       Rao

In [23]:
df.at[10,"Marks"]

np.int64(66)

In [24]:
df.filter(items=["First_Name","Department","CGPA"])

    First_Name Department  CGPA
0        Rohan        MBA  7.22
1         Teja        MBA  6.98
2        Meera         AI  9.04
3       Aditya        MBA  8.62
4       Aditya        CSE  7.24
..         ...        ...   ...
295      Akash         DS  5.96
296      Divya         AI  5.93
297      Sneha        EEE  6.40
298        Sai      CIVIL  5.99
299      Kiran        MBA  9.35

[300 rows x 3 columns]

In [26]:
df.rename(columns={"Marks":"Total_Marks"})

,Student_ID,First_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Total_Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
0,1215,Rohan,Yadav,24,Female,MBA,1,7.22,77.0,57,Warangal,Java,Placed,No,False,2023-04-02
1,1287,Teja,Sharma,21,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Patel,20,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Gupta,19,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
4,1225,Aditya,Rao,22,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1092,Akash,Kumar,23,Female,DS,2,5.96,66.0,60,Bangalore,SQL,Placed,Yes,True,2024-09-01
296,1082,Divya,Sharma,19,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,No,True,2023-02-25
297,1229,Sneha,Reddy,24,Male,EEE,4,6.40,51.0,61,Bangalore,Cloud,Not Placed,Yes,False,2024-05-14
298,1072,Sai,Verma,23,Female,CIVIL,3,5.99,NaN,95,Hyderabad,SQL,Not Placed,Yes,True,2023-10-13
299,1264,Kiran,Sharma,25,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,Yes,False,2023-02-27

In [27]:
df.drop(columns=["Scholarship"])

,Student_ID,First_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Fee_Paid,Admission_Date
0,1215,Rohan,Yadav,24,Female,MBA,1,7.22,77.0,57,Warangal,Java,Placed,False,2023-04-02
1,1287,Teja,Sharma,21,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,False,2022-06-22
2,1235,Meera,Patel,20,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,False,2022-02-08
3,1065,Aditya,Gupta,19,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,False,2023-03-18
4,1225,Aditya,Rao,22,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,False,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1092,Akash,Kumar,23,Female,DS,2,5.96,66.0,60,Bangalore,SQL,Placed,True,2024-09-01
296,1082,Divya,Sharma,19,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,True,2023-02-25
297,1229,Sneha,Reddy,24,Male,EEE,4,6.40,51.0,61,Bangalore,Cloud,Not Placed,False,2024-05-14
298,1072,Sai,Verma,23,Female,CIVIL,3,5.99,NaN,95,Hyderabad,SQL,Not Placed,True,2023-10-13
299,1264,Kiran,Sharma,25,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,False,2023-02-27

In [28]:
df.insert(2,"Full_Name",df["First_Name"] + " " + df["Last_Name"])

In [29]:
df

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
0,1215,Rohan,Rohan Yadav,Yadav,24,Female,MBA,1,7.22,77.0,57,Warangal,Java,Placed,No,False,2023-04-02
1,1287,Teja,Teja Sharma,Sharma,21,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Meera Patel,Patel,20,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Aditya Gupta,Gupta,19,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
4,1225,Aditya,Aditya Rao,Rao,22,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1092,Akash,Akash Kumar,Kumar,23,Female,DS,2,5.96,66.0,60,Bangalore,SQL,Placed,Yes,True,2024-09-01
296,1082,Divya,Divya Sharma,Sharma,19,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,No,True,2023-02-25
297,1229,Sneha,Sneha Reddy,Reddy,24,Male,EEE,4,6.40,51.0,61,Bangalore,Cloud,Not Placed,Yes,False,2024-05-14
298,1072,Sai,Sai Verma,Verma,23,Female,CIVIL,3,5.99,NaN,95,Hyderabad,SQL,Not Placed,Yes,True,2023-10-13
299,1264,Kiran,Kiran Sharma,Sharma,25,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,Yes,False,2023-02-27

In [30]:
df["Age"] = df["Age"].astype("float")

In [31]:
df

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
0,1215,Rohan,Rohan Yadav,Yadav,24.0,Female,MBA,1,7.22,77.0,57,Warangal,Java,Placed,No,False,2023-04-02
1,1287,Teja,Teja Sharma,Sharma,21.0,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Meera Patel,Patel,20.0,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Aditya Gupta,Gupta,19.0,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
4,1225,Aditya,Aditya Rao,Rao,22.0,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1092,Akash,Akash Kumar,Kumar,23.0,Female,DS,2,5.96,66.0,60,Bangalore,SQL,Placed,Yes,True,2024-09-01
296,1082,Divya,Divya Sharma,Sharma,19.0,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,No,True,2023-02-25
297,1229,Sneha,Sneha Reddy,Reddy,24.0,Male,EEE,4,6.40,51.0,61,Bangalore,Cloud,Not Placed,Yes,False,2024-05-14
298,1072,Sai,Sai Verma,Verma,23.0,Female,CIVIL,3,5.99,NaN,95,Hyderabad,SQL,Not Placed,Yes,True,2023-10-13
299,1264,Kiran,Kiran Sharma,Sharma,25.0,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,Yes,False,2023-02-27

In [32]:
df.isnull().sum()

Student_ID        0
First_Name        0
Full_Name         0
Last_Name         0
Age               0
Gender            0
Department        0
Year              0
CGPA              8
Attendance        8
Marks             0
City              8
Course            0
Placement         0
Scholarship       0
Fee_Paid          0
Admission_Date    0
dtype: int64

In [ ]:

df.replace({"Placed":"Selected"})

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
0,1215,Rohan,Rohan Yadav,Yadav,24.0,Female,MBA,1,7.22,77.0,57,Warangal,Java,Selected,No,False,2023-04-02
1,1287,Teja,Teja Sharma,Sharma,21.0,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Meera Patel,Patel,20.0,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Aditya Gupta,Gupta,19.0,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
4,1225,Aditya,Aditya Rao,Rao,22.0,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1092,Akash,Akash Kumar,Kumar,23.0,Female,DS,2,5.96,66.0,60,Bangalore,SQL,Selected,Yes,True,2024-09-01
296,1082,Divya,Divya Sharma,Sharma,19.0,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Selected,No,True,2023-02-25
297,1229,Sneha,Sneha Reddy,Reddy,24.0,Male,EEE,4,6.40,51.0,61,Bangalore,Cloud,Not Placed,Yes,False,2024-05-14
298,1072,Sai,Sai Verma,Verma,23.0,Female,CIVIL,3,5.99,NaN,95,Hyderabad,SQL,Not Placed,Yes,True,2023-10-13
299,1264,Kiran,Kiran Sharma,Sharma,25.0,Female,MBA,1,9.35,78.0,75,Chennai,AI,Selected,Yes,False,2023-02-27

In [34]:
df.sort_values(by="CGPA")

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
266,1193,Divya,Divya Sharma,Sharma,20.0,Male,MBA,1,5.54,71.0,50,Tirupati,Cloud,Placed,No,True,2022-08-23
108,1201,Teja,Teja Yadav,Yadav,18.0,Female,DS,1,5.56,58.0,36,Bangalore,AI,Not Placed,No,True,2023-01-16
120,1077,Varun,Varun Naidu,Naidu,20.0,Male,CSE,2,5.57,100.0,65,Warangal,Python,Placed,No,True,2022-05-10
94,1198,Harsha,Harsha Gupta,Gupta,23.0,Male,MBA,1,5.58,54.0,36,Visakhapatnam,Java,Placed,Yes,False,2023-06-03
92,1125,Rohan,Rohan Verma,Verma,25.0,Female,EEE,4,5.60,75.0,99,Guntur,Java,Placed,No,True,2022-02-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,1027,Priya,Priya Naidu,Naidu,19.0,Female,MECH,4,NaN,84.0,77,Hyderabad,Python,Not Placed,Yes,False,2022-02-09
145,1163,Harsha,Harsha Verma,Verma,22.0,Male,AI,3,NaN,86.0,39,Bangalore,Data Science,Placed,Yes,True,2024-02-10
207,1162,Pooja,Pooja Singh,Singh,25.0,Male,CSE,2,NaN,77.0,77,Chennai,SQL,Placed,Yes,True,2024-07-11
265,1194,Pooja,Pooja Sharma,Sharma,19.0,Male,MECH,3,NaN,58.0,83,Bangalore,Cloud,Placed,Yes,True,2023-09-17
281,1022,Sai,Sai Sharma,Sharma,20.0,Female,EEE,2,NaN,63.0,68,Guntur,Data Science,Placed,Yes,False,2024-04-29

In [37]:
df.sort_values(by="CGPA",ascending=False)

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
213,1012,Teja,Teja Gupta,Gupta,21.0,Male,EEE,4,9.98,91.0,82,Guntur,SQL,Not Placed,Yes,True,2022-08-19
41,1161,Pooja,Pooja Sharma,Sharma,23.0,Female,MBA,2,9.96,64.0,73,Chennai,Cloud,Placed,Yes,False,2023-01-24
40,1017,Arjun,Arjun Gupta,Gupta,18.0,Male,CIVIL,1,9.93,66.0,93,Visakhapatnam,AI,Not Placed,Yes,True,2022-10-31
222,1224,Divya,Divya Patel,Patel,23.0,Male,ECE,3,9.92,60.0,46,Warangal,AI,Placed,No,True,2022-09-13
33,1187,Vihaan,Vihaan Yadav,Yadav,23.0,Female,DS,3,9.91,68.0,72,Visakhapatnam,SQL,Placed,Yes,False,2024-07-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,1027,Priya,Priya Naidu,Naidu,19.0,Female,MECH,4,NaN,84.0,77,Hyderabad,Python,Not Placed,Yes,False,2022-02-09
145,1163,Harsha,Harsha Verma,Verma,22.0,Male,AI,3,NaN,86.0,39,Bangalore,Data Science,Placed,Yes,True,2024-02-10
207,1162,Pooja,Pooja Singh,Singh,25.0,Male,CSE,2,NaN,77.0,77,Chennai,SQL,Placed,Yes,True,2024-07-11
265,1194,Pooja,Pooja Sharma,Sharma,19.0,Male,MECH,3,NaN,58.0,83,Bangalore,Cloud,Placed,Yes,True,2023-09-17
281,1022,Sai,Sai Sharma,Sharma,20.0,Female,EEE,2,NaN,63.0,68,Guntur,Data Science,Placed,Yes,False,2024-04-29

In [38]:
df.nlargest(5,"Marks")

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
68,1270,Priya,Priya Naidu,Naidu,25.0,Male,DS,4,8.21,97.0,100,Visakhapatnam,Cloud,Not Placed,Yes,True,2022-08-03
34,1094,Kavya,Kavya Verma,Verma,18.0,Male,MECH,3,5.85,55.0,99,Tirupati,AI,Placed,No,True,2022-11-26
54,1183,Kavya,Kavya Yadav,Yadav,18.0,Female,CSE,4,6.11,74.0,99,NaN,AI,Not Placed,No,False,2023-05-16
92,1125,Rohan,Rohan Verma,Verma,25.0,Female,EEE,4,5.60,75.0,99,Guntur,Java,Placed,No,True,2022-02-21
219,1042,Ananya,Ananya Yadav,Yadav,19.0,Male,MECH,4,8.48,54.0,99,Warangal,Python,Not Placed,No,True,2023-03-20

In [40]:
df.query("CGPA > 8")

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
2,1235,Meera,Meera Patel,Patel,20.0,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
3,1065,Aditya,Aditya Gupta,Gupta,19.0,Male,MBA,2,8.62,51.0,40,Warangal,Python,Not Placed,No,False,2023-03-18
5,1158,Varun,Varun Verma,Verma,20.0,Male,CSE,1,9.75,92.0,41,Hyderabad,AI,Placed,Yes,True,2023-12-26
11,1265,Vihaan,Vihaan Singh,Singh,18.0,Male,EEE,2,8.45,79.0,78,Warangal,Python,Placed,No,False,2023-07-28
12,1138,Divya,Divya Patel,Patel,22.0,Male,CSE,3,8.06,56.0,77,Visakhapatnam,AI,Not Placed,Yes,False,2022-10-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,1199,Ananya,Ananya Singh,Singh,24.0,Female,CIVIL,1,8.38,84.0,54,Visakhapatnam,Python,Not Placed,Yes,True,2024-09-24
286,1119,Aditya,Aditya Verma,Verma,25.0,Female,DS,2,8.96,NaN,90,Hyderabad,Python,Placed,No,True,2022-06-15
287,1250,Aditya,Aditya Patel,Patel,24.0,Female,CIVIL,4,9.84,74.0,35,Hyderabad,SQL,Placed,No,True,2024-07-02
293,1204,Vihaan,Vihaan Verma,Verma,23.0,Female,DS,2,9.69,52.0,88,Vijayawada,Data Science,Placed,No,False,2022-10-05
299,1264,Kiran,Kiran Sharma,Sharma,25.0,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,Yes,False,2023-02-27

In [41]:
df[df["Department"].isin(["CSE","AI"])]

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
2,1235,Meera,Meera Patel,Patel,20.0,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
4,1225,Aditya,Aditya Rao,Rao,22.0,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
5,1158,Varun,Varun Verma,Verma,20.0,Male,CSE,1,9.75,92.0,41,Hyderabad,AI,Placed,Yes,True,2023-12-26
10,1278,Teja,Teja Singh,Singh,25.0,Male,AI,3,7.51,91.0,66,Hyderabad,Cloud,Not Placed,No,True,2023-01-31
12,1138,Divya,Divya Patel,Patel,22.0,Male,CSE,3,8.06,56.0,77,Visakhapatnam,AI,Not Placed,Yes,False,2022-10-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,1166,Pooja,Pooja Gupta,Gupta,20.0,Female,AI,3,9.09,95.0,44,Chennai,Data Science,Placed,No,True,2024-01-28
282,1120,Priya,Priya Kumar,Kumar,23.0,Female,AI,3,6.38,85.0,70,Bangalore,Cloud,Not Placed,Yes,True,2023-08-30
284,1136,Akash,Akash Kumar,Kumar,21.0,Male,AI,4,6.99,80.0,47,Bangalore,Python,Placed,No,False,2023-05-04
294,1290,Harsha,Harsha Yadav,Yadav,24.0,Male,CSE,3,7.95,84.0,95,NaN,Data Science,Not Placed,Yes,False,2022-05-18
296,1082,Divya,Divya Sharma,Sharma,19.0,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,No,True,2023-02-25

In [42]:
df[df["Marks"].between(70,90)]

,Student_ID,First_Name,Full_Name,Last_Name,Age,Gender,Department,Year,CGPA,Attendance,Marks,City,Course,Placement,Scholarship,Fee_Paid,Admission_Date
1,1287,Teja,Teja Sharma,Sharma,21.0,Female,MBA,4,6.98,92.0,74,Bangalore,SQL,Not Placed,No,False,2022-06-22
2,1235,Meera,Meera Patel,Patel,20.0,Male,AI,1,9.04,84.0,79,NaN,Data Science,Not Placed,No,False,2022-02-08
4,1225,Aditya,Aditya Rao,Rao,22.0,Male,CSE,1,7.24,96.0,88,Bangalore,AI,Not Placed,No,False,2023-07-14
8,1196,Meera,Meera Rao,Rao,20.0,Male,EEE,1,6.62,88.0,71,Hyderabad,Cloud,Not Placed,Yes,True,2024-02-05
11,1265,Vihaan,Vihaan Singh,Singh,18.0,Male,EEE,2,8.45,79.0,78,Warangal,Python,Placed,No,False,2023-07-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,1021,Sneha,Sneha Sharma,Sharma,21.0,Female,EEE,2,7.47,84.0,73,Hyderabad,Cloud,Not Placed,Yes,True,2022-09-28
290,1184,Rohan,Rohan Sharma,Sharma,18.0,Male,EEE,1,6.74,84.0,71,Bangalore,AI,Not Placed,Yes,True,2022-10-02
293,1204,Vihaan,Vihaan Verma,Verma,23.0,Female,DS,2,9.69,52.0,88,Vijayawada,Data Science,Placed,No,False,2022-10-05
296,1082,Divya,Divya Sharma,Sharma,19.0,Male,AI,4,5.93,97.0,82,Bangalore,SQL,Placed,No,True,2023-02-25
299,1264,Kiran,Kiran Sharma,Sharma,25.0,Female,MBA,1,9.35,78.0,75,Chennai,AI,Placed,Yes,False,2023-02-27

In [43]:
df.groupby("Department")["CGPA"].mean()

Department
AI       7.921333
CIVIL    7.764872
CSE      7.792121
DS       7.578409
ECE      7.962647
EEE      7.627576
MBA      7.879512
MECH     7.875789
Name: CGPA, dtype: float64

In [44]:
df.groupby("Department")["Marks"].agg(["mean","max"])

                 mean  max
Department
AI          68.935484   96
CIVIL       69.769231   98
CSE         70.285714   99
DS          67.295455  100
ECE         61.411765   97
EEE         69.916667   99
MBA         63.439024   97
MECH        73.100000   99